### ISSUE TITLE
雕像生成速度过快导致服务器崩溃

### ISSUE THREAD

**Issue by CNZW-WTW** [Jeryn99/Weeping-Angels#347]
在主世界时，雕像几乎不会生成，但是当我前往下界是，雕像生成速度可达1秒10个，导致我的服务器崩溃，只能使用命令方块/kill
![微信图片_20240329212311](https://github.com/Jeryn99/Weeping-Angels/assets/146963503/f3141119-d019-41f4-9b45-2d32076498fc)
![微信图片_20240329212333](https://github.com/Jeryn99/Weeping-Angels/assets/146963503/2a367633-b543-4559-a59a-f87b905ce2cb)

**Comment by CNZW-WTW** [comment]
生成速度过快，让我无法在下界探险

**Comment by Jeryn99** [comment]
您可以在配置文件中调整这些内容 - 我将在本周晚些时候发布一个修复程序，解决这个错误的问题
